name: KEEP_ACTIVE

permissions:
  contents: write

on:
  schedule:
    - cron: "0 15 1 * *"
  workflow_dispatch:

jobs:
  build:
    name: Keep Active
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 覚書
      # https://blog.3qe.us/entry/2020/02/17/164535
      - name: Commit
        run: |
            echo `date +%Y%m%d%H%M%S` > version.txt

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Auto Commit