name: BUILD

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
    branches: [ develop ]

jobs:
  build:
    name: Build csv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate version file
        run: |
          echo `date +%Y%m%d%H%M%S` > version.txt

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Auto Commit

      - name: Generate Csv
        run: |
          mkdir out
          python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: |
          set -x
          cd out
          assets=()
          assets+=("-a" "./outcome.csv")
          tag_name=`date '+%Y%m%d%H%M'`
          hub release create "${assets[@]}" -m "Latest" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}